services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app_admin
      POSTGRES_PASSWORD: StrongPass1!
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dbnet

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: StrongPass1!
      MYSQL_DATABASE: library_db
      MYSQL_USER: app_admin
      MYSQL_PASSWORD: StrongPass2!
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - dbnet

  oracle_db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle_db
    restart: unless-stopped
    environment:
      ORACLE_PWD: StrongPass1!
    ports:
      - "1521:1521"
    volumes:
      - oracledata:/opt/oracle/oradata
    networks:
      - dbnet

  mongo_db:
    image: mongo:6.0
    container_name: mongo_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: app_admin
      MONGO_INITDB_ROOT_PASSWORD: StrongPass1!
      MONGO_INITDB_DATABASE: library_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - dbnet

  api:
    build: .
    container_name: library_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - mysql_db
      - oracle_db
      - mongo_db
    networks:
      - dbnet

volumes:
  pgdata:
  mysqldata:
  oracledata:
  mongodata:

networks:
  dbnet:
    driver: bridge